{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Calculadora\n",
      "Bem vindo a Calculadora\n",
      "Opções:\n",
      "1. Soma\n",
      "2. Subtração\n",
      "3. Multiplicação\n",
      "4. Divisão\n",
      "5. Sair\n",
      "Essa opção não existe. Tente novamente.\n",
      "Calculadora\n",
      "Bem vindo a Calculadora\n",
      "Opções:\n",
      "1. Soma\n",
      "2. Subtração\n",
      "3. Multiplicação\n",
      "4. Divisão\n",
      "5. Sair\n",
      "Erro: Divisão por zero!\n",
      "Calculadora\n",
      "Bem vindo a Calculadora\n",
      "Opções:\n",
      "1. Soma\n",
      "2. Subtração\n",
      "3. Multiplicação\n",
      "4. Divisão\n",
      "5. Sair\n",
      "Essa opção não existe. Tente novamente.\n",
      "Calculadora\n",
      "Bem vindo a Calculadora\n",
      "Opções:\n",
      "1. Soma\n",
      "2. Subtração\n",
      "3. Multiplicação\n",
      "4. Divisão\n",
      "5. Sair\n",
      "Essa opção não existe. Tente novamente.\n",
      "Calculadora\n",
      "Bem vindo a Calculadora\n",
      "Opções:\n",
      "1. Soma\n",
      "2. Subtração\n",
      "3. Multiplicação\n",
      "4. Divisão\n",
      "5. Sair\n",
      "Encerrando a calculadora. Até mais!\n"
     ]
    }
   ],
   "source": [
    "def calculadora():\n",
    "    while True:\n",
    "        print(\"Calculadora\")\n",
    "        print(\"Bem vindo a Calculadora\")\n",
    "        print(\"Opções:\")\n",
    "        print(\"1. Soma\")\n",
    "        print(\"2. Subtração\")\n",
    "        print(\"3. Multiplicação\")\n",
    "        print(\"4. Divisão\")\n",
    "        print(\"0. Sair\")\n",
    "\n",
    "        operacao = input(\"Digite o número para a operação correspondente: \")\n",
    "\n",
    "        if operacao == '0':\n",
    "            print(\"Encerrando a calculadora. Até mais!\")\n",
    "            break\n",
    "\n",
    "        if operacao not in ['1', '2', '3', '4']:\n",
    "            print(\"Essa opção não existe. Tente novamente.\")\n",
    "            continue\n",
    "\n",
    "        try:\n",
    "            numero1 = float(input(\"Digite o Primeiro Numero: \"))\n",
    "            numero2 = float(input(\"Digite o Segundo Numero: \"))\n",
    "        except ValueError:\n",
    "            print(\"Erro: Insira valores numéricos válidos.\")\n",
    "            continue\n",
    "\n",
    "        def realizar_operacao(numero1, numero2, operacao):\n",
    "            if operacao == '1':\n",
    "                resultado = numero1 + numero2\n",
    "                print(\"A soma de {} com {} é igual a: {}\".format(numero1, numero2, resultado))\n",
    "            elif operacao == '2':\n",
    "                resultado = numero1 - numero2\n",
    "                print(\"A subtração de {} por {} é igual a: {}\".format(numero1, numero2, resultado))\n",
    "            elif operacao == '3':\n",
    "                resultado = numero1 * numero2\n",
    "                print(\"A multiplicação de {} por {} é igual a: {}\".format(numero1, numero2, resultado))\n",
    "            elif operacao == '4':\n",
    "                if numero2 != 0:\n",
    "                    resultado = numero1 / numero2\n",
    "                    print(\"A divisão de {} por {} é igual a: {}\".format(numero1, numero2, resultado))\n",
    "                else:\n",
    "                    print(\"Erro: Divisão por zero!\")\n",
    "\n",
    "        realizar_operacao(numero1, numero2, operacao)\n",
    "\n",
    "# Chame a função para iniciar a calculadora\n",
    "calculadora()\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
